apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-api.fullname" . }}
  labels:
    {{- include "llama-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "llama-api.selectorLabels" . | nindent 4 }}