name: "CI/CD: Build and Deploy to GKE using Helm"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: nishankkoul/tinyllama-server
      CHART_DIR: helm-tinyllama
      PROJECT_ID: future-campaign-467305-q6
      CLUSTER_NAME: tinyllama-inference-cluster
      CLUSTER_ZONE: us-central1-a

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download model from GCS
        run: |
          mkdir -p models
          curl -o models/tinyllama.gguf "https://storage.googleapis.com/tinyllama--model-nishank/tinyllama.gguf"

      - name: Extract current image tag from values.yaml
        id: get_tag
        run: |
          tag=$(grep 'tag:' $CHART_DIR/values.yaml | awk '{print $2}' | tr -d '"')
          version_number=${tag#v}
          next_version=$(awk -F. -v OFS=. '{$NF++; print}' <<< "$version_number")
          echo "next_tag=v$next_version" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          next_tag="${{ steps.get_tag.outputs.next_tag }}"
          echo "Tag is: $next_tag"
          docker build -t $DOCKER_REPO:$next_tag .
          docker push $DOCKER_REPO:$next_tag

      - name: Update Helm values.yaml with new tag
        run: |
          next_tag="${{ steps.get_tag.outputs.next_tag }}"
          sed -i "s/tag: .*/tag: \"$next_tag\"/" $CHART_DIR/values.yaml

      - name: Commit updated values.yaml and skip CI
        run: |
          next_tag="${{ steps.get_tag.outputs.next_tag }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $CHART_DIR/values.yaml
          git commit -m "Update image tag to $next_tag [skip ci]" || echo "No changes to commit"
          git push

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $CLUSTER_ZONE \
            --project $PROJECT_ID

      - name: Helm Lint
        run: |
          helm lint $CHART_DIR

      - name: Helm Dry Run
        run: |
          helm upgrade --install tinyllama $CHART_DIR \
            --namespace default \
            --dry-run \
            --debug

      - name: Helm Deploy to GKE
        run: |
          helm upgrade --install tinyllama $CHART_DIR \
            --namespace default \
            --wait
